package svl.kadatha.filex;

public enum FileObjectType {
    ROOT_TYPE, FILE_TYPE, SEARCH_LIBRARY_TYPE, USB_TYPE, FTP_TYPE, SFTP_TYPE, WEBDAV_TYPE, SMB_TYPE,
    GOOGLE_DRIVE_TYPE,ONE_DRIVE_TYPE,DROP_BOX_TYPE,MEDIA_FIRE_TYPE,
}
